### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pixelkoduje** [pushpender-singh-ap/react-native-peer#1]
why do you return simple true?  and why was this code removed?  And the second question is, does it work without any problems?  By returning true, does this cause any problems?  Is the library working?

` 	isUnifiedPlanSupported(): boolean {
-		const browser = this.getBrowser();
-		const version = webRTCAdapter.browserDetails.version || 0;
-
-		if (browser === "chrome" && version < this.minChromeVersion) return false;
-		if (browser === "firefox" && version >= this.minFirefoxVersion) return true;
-		if (
-			!window.RTCRtpTransceiver ||
-			!("currentDirection" in RTCRtpTransceiver.prototype)
-		)
-			return false;
-
-		let tempPc: RTCPeerConnection;
-		let supported = false;
-
-		try {
-			tempPc = new RTCPeerConnection();
-			tempPc.addTransceiver("audio");
-			supported = true;
-		} catch (e) {
-		} finally {
-			if (tempPc) {
-				tempPc.close();
-			}
-		}
-
-		return supported;
+		return true;
 	}
`

**Comment by pushpender-singh-ap** [comment]
@pixelkoduje I am also using this library it's working fine without any issue. Install the latest version v1.1.0
